project_id = "oahfilsbvcvgyrcducbq"

[functions.send-reminder-email]
verify_jwt = false

[functions.check-reminders]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false
